// <auto-generated />
using System;
using EvidenceChain.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvidenceChain.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913040102_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EvidenceChain.Api.Domain.CustodyEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<byte>("EventType")
                        .HasColumnType("tinyint");

                    b.Property<int>("EvidenceId")
                        .HasColumnType("int");

                    b.Property<int?>("FromCustodianId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int?>("ToCustodianId")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransferId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("FromCustodianId");

                    b.HasIndex("ToCustodianId");

                    b.HasIndex("TransferId");

                    b.HasIndex("EvidenceId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("UX_CustodyEvents_Evidence_Seq");

                    b.ToTable("CustodyEvents", null, t =>
                        {
                            t.HasTrigger("TR_CustodyEvents_AppendOnly");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("EvidenceChain.Api.Domain.CustodyTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EvidenceId")
                        .HasColumnType("int");

                    b.Property<int>("FromCustodianId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("RespondedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ResponseNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("ToCustodianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceId")
                        .IsUnique()
                        .HasDatabaseName("UX_Transfer_OnePendingPerEvidence")
                        .HasFilter("[Status] = 0");

                    b.HasIndex("FromCustodianId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("RespondedByUserId");

                    b.HasIndex("ToCustodianId");

                    b.HasIndex("Status", "RequestedAtUtc")
                        .HasDatabaseName("IX_Transfer_PendingAge");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "RequestedAtUtc"), new[] { "EvidenceId", "ToCustodianId" });

                    b.ToTable("CustodyTransfers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transfer_DistinctCustodians", "[FromCustodianId] <> [ToCustodianId]");
                        });
                });

            modelBuilder.Entity("EvidenceChain.Api.Domain.Evidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("CurrentCustodianId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("IntegrityCheckedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("IntegrityStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("LastEventAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Evidence_Code");

                    b.HasIndex("LastEventAtUtc", "Id")
                        .IsDescending()
                        .HasDatabaseName("IX_Evidence_Keyset");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("LastEventAtUtc", "Id"), new[] { "Code", "Description", "CurrentCustodianId", "IntegrityStatus" });

                    b.HasIndex("CurrentCustodianId", "LastEventAtUtc", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_Evidence_Custodian_Keyset");

                    b.ToTable("Evidence", (string)null);
                });

            modelBuilder.Entity("EvidenceChain.Api.Domain.IdempotencyRecord", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("UserId", "IdempotencyKey")
                        .HasName("PK_Idempotency");

                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("EvidenceChain.Api.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_UserName");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN (N'Investigador', N'Custodio', N'Supervisor')");
                        });
                });

            modelBuilder.Entity("EvidenceChain.Api.Domain.CustodyEvent", b =>
                {
                    b.HasOne("EvidenceChain.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvidenceChain.Api.Domain.Evidence", null)
                        .WithMany("Events")
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvidenceChain.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("FromCustodianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EvidenceChain.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ToCustodianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EvidenceChain.Api.Domain.CustodyTransfer", null)
                        .WithMany()
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EvidenceChain.Api.Domain.CustodyTransfer", b =>
                {
                    b.HasOne("EvidenceChain.Api.Domain.Evidence", null)
                        .WithMany()
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvidenceChain.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("FromCustodianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvidenceChain.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvidenceChain.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("RespondedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EvidenceChain.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ToCustodianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EvidenceChain.Api.Domain.Evidence", b =>
                {
                    b.HasOne("EvidenceChain.Api.Domain.User", "CurrentCustodian")
                        .WithMany()
                        .HasForeignKey("CurrentCustodianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentCustodian");
                });

            modelBuilder.Entity("EvidenceChain.Api.Domain.Evidence", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
